from typing import List
from .motif import Motif, InvalidMotifException
from .event import Event


class Pattern(Motif):
    """
    Generate motifs from a list of other motifs. The total length of this motif is
    the sum of the length of the motifs passed in. The event positions are
    are generated by accumulating motif lengths over the list of motifs.

    For example, given two motifs [0,.5] and [0,.7], each with length 1, the
    events for this pattern will be [0, .5, 1, 1.7]
    """

    def __init__(self, motifs: List[Motif]):
        """
        Create a motif from a list of existing motifs.
        :param motifs: list of motif instances
        """
        if type(motifs) is not list:
            raise InvalidMotifException(f'Expecting list for Pattern, got {type(motifs)}')

        for i, motif in enumerate(motifs):
            if not issubclass(type(motif), Motif):
                raise InvalidMotifException(
                    f'Invalid type {type(motif)} for Pattern at index {i}'
                )

        self.motifs = motifs

    def length(self) -> float:
        return sum([motif.length() for motif in self.motifs])

    def events(self) -> List[Event]:
        result = []
        offset = 0
        for motif in self.motifs:
            for ev in motif.events():
                result.append(ev.clone_at(ev.pos + offset))
            offset += motif.length()
        return result
