repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2  # use the latest version
    hooks:
      - id: ruff-check
        args: [--no-fix]

      - id: ruff-format
        args: [--check]
