from enum import Enum
from typing import Any, List


class MotifType(Enum):
    """
    Data type generated by a motif

    Motifs can produce MIDI or Audio data
    """

    MIDI = 1
    AUDIO = 2


class Motif:
    """
    Base class for motif-like objects

    Motifs are the foundations of deltabeat, used for generating and transforming
    musical and audio events. Each motif has `count` number of events and for
    each event has two accessors to get the sorted `position` in time for a given
    index and `data` get the value at that point, which has a return type
    dependant on `type`, which is handled higher up in the `Track` and `Score`
    part of the API.

    Position and data are separate for flexibility in expressing data generation;
    a custom motif of programmed notes may be at arbitrary positions, but one
    could also generate them procedurally. The latter is used for audio motifs
    which have periodic events.

    Each motif has a `duration`, and for duration *d*, the range of `position`
    is between [0, *d*).

    The `rate` of deltabeat is used to determine the playback speed relative to
    a base tempo at any point along the motif. It's input value *u* is
    normalised to the range [0, 1].

    Derived motifs must implement all above methods, and fall into two categories:
    a `Source` generates data, for example manually composed events or an audio
    sample, and a `Modifier` transforms an underlying input motif. The latter
    drives how motifs can be bound together and layered in deltabeat, akin to
    image editing software.
    """

    def type(self) -> MotifType:
        raise NotImplementedError(f"Motif.type not implemented for {self}")

    def count(self) -> int:
        raise NotImplementedError(f"Motif.count not implemented for {self}")

    def pos(self, i: int) -> float:
        raise NotImplementedError(f"Motif.pos not implemented for {self}")

    def data(self, i: int) -> Any:
        raise NotImplementedError(f"Motif.data not implemented for {self}")

    def duration(self) -> float:
        raise NotImplementedError(f"Motif.duration not implemented for {self}")

    def rate(self, u: float) -> float:
        return 1.0

    def __str__(self):
        exprs = []
        for i in range(self.count()):
            exprs.append(f"{self.pos(i)}: {self.data(i)}")
        return ", ".join(exprs)


class MotifChain(Motif):
    def __init__(self, motifs: List[Motif]):
        assert len(motifs) > 0
        assert all(m.type() == motifs[0].type() for m in motifs[1:])
        self._motifs = motifs

    def type(self) -> MotifType:
        return self._motifs[0].type()

    def count(self) -> int:
        return sum(m.count() for m in self._motifs)

    def pos(self, i: int):
        m, j, prefix_dur = self._motif_at(i)
        return m.pos(j) + prefix_dur

    def data(self, i: int):
        m, j, _ = self._motif_at(i)
        return m.data(j)

    def duration(self) -> float:
        return sum(m.duration() for m in self._motifs)

    def rate(self, u: float):
        m, v = self._motif_at_frac(u)
        return m.rate(v)

    def _motif_at(self, i: int):
        prefix_dur = .0
        for m in self._motifs:
            if i < m.count():
                return m, i, prefix_dur
            i -= m.count()
            prefix_dur += m.duration()

        return None, None

    def _motif_at_frac(self, u: float):
        # Example scenario
        #   chain   |------|--|----|
        #   dur         7    3    5
        #   acc_dur 0      7  10   15
        #   count   0      1  2    3
        #   fracs:
        #     0 / 15 = (0, 0)       X------|--|----|
        #     1 / 15 = (0, 1/7)     |X-----|--|----|
        #     2 / 15 = (0, 2/7)     |-X----|--|----|
        #     3 / 15 = (0, 3/7)     ...
        #     4 / 15 = (0, 4/7)
        #     5 / 15 = (0, 5/7)
        #     6 / 15 = (0, 6/7)
        #     7 / 15 = (1, 0)
        #     8 / 15 = (1, 1/3)
        #     9 / 15 = (1, 2/3)
        #     10 / 15 = (2, 0)
        #     11 / 15 = (2, 1/5)
        #     12 / 15 = (2, 2/5)    ...
        #     13 / 15 = (2, 3/5)    |------|--|--X-|
        #     14 / 15 = (2, 4/5)    |------|--|---X|
        total_duration = self.duration()
        current_start_pos = .0
        for m in self._motifs:
            next_start_pos = current_start_pos + m.duration()
            start_frac = current_start_pos / total_duration
            next_frac = next_start_pos / total_duration
            if u < next_frac:
                v = (u - start_frac) * (total_duration / m.duration())
                return m, v
            current_start_pos = next_start_pos
        return None, None


class Source(Motif):
    """
    Direct motif data source. Sources have a flat playback rate by default.
    """

    def rate(self, u: float) -> float:
        return 1.0
