from typing import List
from .beat import Beat, InvalidBeatException
from .event import Event


class BeatPattern(Beat):
    """
    Generate beats from a list of other beats. The total length of this beat is
    the sum of the length of the beats passed in. The event positions are
    are generated by accumulating beat lengths over the list of beats.

    For example, given two beats [0,.5] and [0,.7], each with length 1, the
    events for this pattern will be [0, .5, 1, 1.7]
    """

    def __init__(self, beats: List[Beat]):
        """
        Create a beat from a list of existing beats.
        :param beats: list of beat instances
        """
        if type(beats) is not list:
            raise InvalidBeatException(f'Expecting list for BeatPattern, got {type(beats)}')

        for i, beat in enumerate(beats):
            if not issubclass(type(beat), Beat):
                raise InvalidBeatException(
                    f'Invalid type {type(beat)} for BeatPattern at index {i}'
                )

        self.beats = beats

    def length(self) -> float:
        return sum([beat.length() for beat in self.beats])

    def events(self) -> List[Event]:
        result = []
        offset = 0
        for beat in self.beats:
            for ev in beat.events():
                result.append(ev.clone_at(ev.pos + offset))
            offset += beat.length()
        return result
